spring.application.name=KafkaProducer



server.port=1010

spring.kafka.bootstrap-servers=localhost:9092

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayush.raj3645@gmail.com
spring.mail.password=qslamfuisagzyanl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true