# Root logger level
rootLogger.level = trace
rootLogger.appenderRefs = file
rootLogger.appenderRef.file.ref = FileAppender

# File Appender
appender.file.type = File
appender.file.name = FileAppender
appender.file.fileName = logs/app.log

# Layout (log format)
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n